import { AppConversionUnitGenericCreateDto } from './app-conversion-unit-generic-create-dto';
export class AppDetailQuotesUpdateDto {
  appGeneralQuotesId: number;
  cotizacion: string;
  id: number;
  producto: string;
  idProducto: number;
  nombreComercialProducto: string;
  condicionPago: number;
  idEstatus: number;
  cantidad: number;
  cantidadSolicitada: number;
  precio: number;
  total: number;
  precioUsd: number;
  totalUsd: number;
  idUnidad: number;
  observaciones: string;
  diasEntrega: number;
  usuarioConectado: string;
  appConversionUnitGenericCreateDto?: AppConversionUnitGenericCreateDto =
    new AppConversionUnitGenericCreateDto();
  precioLista: number;
  quantityPerPackage: number;
  solicitarPrecio: boolean;
  obsSolicitud: string;
  obsSolicitudSobreprecio: string;
  medidaBasica: string;
  medidaOpuesta: string;
  valorConvertido: number;
  ordenAnterior: number;
  cantidadPorUnidadProduccion: number;
  calculoId: number;
  unitPriceBaseProductionMaximo: number;
  porcMaximoSobrePrecio: number;
  forma: string;
  salida: string;
  presentacion: string;
  eliminarSolicitud: boolean;
}
