import { AppProductsGetDto } from './app-products-get-dto';
import { AppStatusQuoteGetDto } from './app-status-quote-get-dto';
import { AppUnitsGetDto } from './app-units-get-dto';
import { AppTemplateConversionUnitGetDto } from './app-template-conversion-unit-get-dto';
import { StatusAprobacionDto } from './app-status-aprobacion-dto';
import { AppProductConversionGetDto } from './app-product-conversion-get-dto';
import { AppSolicitudAprobacion } from './app-solicitud-aprobacion.model';

export class AppDetailQuotesGetDto {
  id: number;
  appGeneralQuotesId: number;
  cotizacion: string;
  renglon: number;
  propuesta: number;
  producto: string;
  idProducto: number;
  nombreComercialProducto: string;
  idEstatus: number;
  cantidad: number;
  cantidadSolicitada: number;
  precio: number;
  total: number;
  precioUsd: number;
  totalUsd: number;
  idUnidad: number;
  observaciones: string;
  diasEntrega: number;
  usuarioConectado: string;
  valorConvertido: number;
  unitPriceBaseProduction: number;
  unitPriceConverted: number;
  cantidadTintas: number;
  tieneTintasCargadas: boolean;
  calculoId: number;
  AppStatusQuoteGetDto: AppStatusQuoteGetDto;
  appStatusQuoteGetDto: AppStatusQuoteGetDto;
  appUnitsGetDto: AppUnitsGetDto;
  quantityPerPackage: number;
  obsSolicitud: string;
  obsSolicitudSobreprecio: string;
  cantidadPorUnidadProduccion: number;
  appTemplateConversionUnitGetDto: AppTemplateConversionUnitGetDto[] = [];
  statusAprobacionDto: StatusAprobacionDto;
  statusAprobacionSobreprecioDto: StatusAprobacionDto;
  appSolicitudAprobacionDto: AppSolicitudAprobacion;
  medidaBasica: string;
  medidaOpuesta: string;
  ordenAnterior: number;
  appProductConversionGetDto: AppProductConversionGetDto;
  appProductsGetDto: AppProductsGetDto;

  forma: string;
  salida: string;
  presentacion: string;
  flete: number;
  porcFlete: number;
  solicitarPrecio: boolean;
  mensajeSolicitarPrecio: string;
  estimada: boolean;
  precioMaximo: number;
  fleteMaximo: number;
  porcMaximoSobrePrecio: number;
}
