-- PRE.PRE_V_DOC_BLOQUEADO source

CREATE OR REPLACE FORCE VIEW "PRE"."PRE_V_DOC_BLOQUEADO" ("DESCRIPCION", "CODIGO_SALDO", "CODIGO_PRESUPUESTO", "NUMERO1", "NUMERO", "FECHA", "MOTIVO", "MONTO") AS
  SELECT     PRE_f_descriptivas ('A.DESCRIPCION', 'TCP'
        ,'DESCRIPCION_ID',TIPO_MODIFICACION_ID,A.CODIGO_EMPRESA)DESCRIPCION  --MODIFICACION PRESUPUESTARIA (TRASPASO)
        ,B.CODIGO_SALDO
        ,A.CODIGO_PRESUPUESTO
        ,A.CODIGO_SOL_MODIFICACION NUMERO1
        ,A.NUMERO_SOL_MODIFICACION NUMERO
        ,A.FECHA_SOLICITUD FECHA
        ,A.MOTIVO
        ,SUM(B.MONTO) MONTO
    FROM PRE_SOL_MODIFICACION A
        ,PRE_PUC_SOL_MODIFICACION B
        WHERE  B.CODIGO_SOL_MODIFICACION = A.CODIGO_SOL_MODIFICACION
     AND A.STATUS = 'PE'
     AND B.DE_PARA = 'D'
     GROUP
      BY PRE_f_descriptivas ('A.DESCRIPCION', 'TCP'
        ,'DESCRIPCION_ID',TIPO_MODIFICACION_ID,A.CODIGO_EMPRESA)
        ,B.CODIGO_SALDO
        ,A.CODIGO_PRESUPUESTO
        ,A.CODIGO_SOL_MODIFICACION
        ,A.FECHA_SOLICITUD
        ,A.NUMERO_SOL_MODIFICACION
        ,A.MOTIVO
  UNION ALL
  SELECT
                adm_f_descriptivas ('A.DESCRIPCION', 'MCTRL'
              ,'CODIGO','COM',A.CODIGO_EMPRESA)DESCRIPCION  --'Compromiso Administrativo' ORIGEN
        ,B.CODIGO_SALDO
        ,A.CODIGO_PRESUPUESTO
        ,A.CODIGO_SOL_COMPROMISO NUMERO1
        ,A.NUMERO_SOLICITUD NUMERO
        ,A.FECHA_SOLICITUD FECHA
        ,A.MOTIVO
        ,SUM(B.MONTO) MONTO
    FROM ADM_SOL_COMPROMISO A
        ,ADM_PUC_SOL_COMPROMISO B
        WHERE B.CODIGO_SOLICITUD = A.CODIGO_SOL_COMPROMISO
     AND A.STATUS = 'PE'
     AND B.MONTO > 0
     GROUP
      BY adm_f_descriptivas ('A.DESCRIPCION', 'MCTRL'
              ,'CODIGO','COM',A.CODIGO_EMPRESA)
        ,B.CODIGO_SALDO
        ,A.CODIGO_PRESUPUESTO
        ,A.CODIGO_SOL_COMPROMISO
        ,A.FECHA_SOLICITUD
        ,A.NUMERO_SOLICITUD
        ,A.MOTIVO
  UNION ALL
  SELECT adm_f_descriptivas ('A.DESCRIPCION', 'MCTRL','CODIGO','ODC'
                ,A.CODIGO_EMPRESA)DESCRIPCION    ----'Compras' ORIGEN
        ,C.CODIGO_SALDO
        ,A.CODIGO_PRESUPUESTO
        ,A.CODIGO_REQUISICION NUMERO1
        ,A.NUMERO_REQUISICION NUMERO
        ,A.FECHA_REQUISICION FECHA
        ,A.MOTIVO
        ,SUM(C.MONTO) MONTO
    FROM ADM_REQUISICIONES A
        ,ADM_DETALLE_REQUISICION B
        ,ADM_PUC_REQUISICION C
         WHERE B.CODIGO_REQUISICION = A.CODIGO_REQUISICION
     AND C.CODIGO_DETALLE_REQUISICION = B.CODIGO_DETALLE_REQUISICION
     AND A.STATUS = 'PE'
     AND C.MONTO > 0
     GROUP
      BY adm_f_descriptivas ('A.DESCRIPCION', 'MCTRL'
              ,'CODIGO','ODC',A.CODIGO_EMPRESA)
        ,C.CODIGO_SALDO
        ,A.CODIGO_PRESUPUESTO
        ,A.CODIGO_REQUISICION
        ,A.FECHA_REQUISICION
        ,A.NUMERO_REQUISICION
        ,A.MOTIVO
     UNION ALL
  SELECT
                adm_f_descriptivas ('A.DESCRIPCION', 'MCTRL'
              ,'CODIGO','COM',A.CODIGO_EMPRESA)DESCRIPCION  --'Compromiso Administrativo' ORIGEN
        ,C.CODIGO_SALDO
        ,A.CODIGO_PRESUPUESTO
        ,A.CODIGO_SOLICITUD NUMERO1
        ,A.NUMERO_SOLICITUD NUMERO
        ,A.FECHA_SOLICITUD FECHA
        ,A.MOTIVO
        ,SUM(C.MONTO) MONTO
    FROM ADM_SOLICITUDES A
        ,ADM_DETALLE_SOLICITUD B
        ,ADM_PUC_SOLICITUD C
        WHERE A.CODIGO_SOLICITUD = B.CODIGO_SOLICITUD
     AND B.CODIGO_DETALLE_SOLICITUD = C.CODIGO_DETALLE_SOLICITUD
     AND A.STATUS = 'PE'
     AND C.MONTO > 0
     GROUP
      BY adm_f_descriptivas ('A.DESCRIPCION', 'MCTRL'
              ,'CODIGO','COM',A.CODIGO_EMPRESA)
        ,C.CODIGO_SALDO
        ,A.CODIGO_PRESUPUESTO
        ,A.CODIGO_SOLICITUD
        ,A.FECHA_SOLICITUD
        ,A.NUMERO_SOLICITUD
        ,A.MOTIVO
;


CREATE OR REPLACE FORCE VIEW "PRE"."PRE_V_DOC_CAUSADO" ("CODIGO_SALDO", "CODIGO_PRESUPUESTO", "NUMERO", "FECHA", "MOTIVO", "MONTO") AS
  SELECT B.CODIGO_SALDO
        ,A.CODIGO_PRESUPUESTO
        ,A.NUMERO_ORDEN_PAGO NUMERO
        ,A.FECHA_ORDEN_PAGO FECHA
        ,A.MOTIVO
        ,SUM(B.MONTO-B.MONTO_ANULADO) MONTO
    FROM ADM_ORDEN_PAGO A
        ,ADM_PUC_ORDEN_PAGO B
        ,ADM_DESCRIPTIVAS D
   WHERE B.CODIGO_ORDEN_PAGO = A.CODIGO_ORDEN_PAGO
     AND A.STATUS != 'AN'
     AND B.MONTO > 0
     AND D.DESCRIPCION_ID = A.TIPO_ORDEN_PAGO_ID
     AND D.CODIGO <> 'P'
   GROUP
      BY B.CODIGO_SALDO
        ,A.CODIGO_PRESUPUESTO
        ,A.NUMERO_ORDEN_PAGO
        ,A.FECHA_ORDEN_PAGO
        ,A.MOTIVO
   UNION ALL
  SELECT B.CODIGO_SALDO
        ,A.CODIGO_PRESUPUESTO
        ,A.NUMERO_ORDEN_PAGO NUMERO
        ,A.FECHA_ORDEN_PAGO FECHA
        ,A.MOTIVO
        ,ROUND((SUM(B.MONTO-B.MONTO_ANULADO)*E.MONTO)/D.MONTO,2) MONTO
    FROM ADM_ORDEN_PAGO A
        ,ADM_PUC_ORDEN_PAGO B
        ,ADM_DESCRIPTIVAS C
        ,(
  SELECT CODIGO_ORDEN_PAGO
        ,SUM(MONTO) MONTO
    FROM ADM_PUC_ORDEN_PAGO
   GROUP BY CODIGO_ORDEN_PAGO
         ) D
        ,(
  SELECT CODIGO_ORDEN_PAGO
        ,SUM(MONTO) MONTO
    FROM ADM_PERIODICO_OP
   GROUP BY CODIGO_ORDEN_PAGO
         ) E
   WHERE B.CODIGO_ORDEN_PAGO = A.CODIGO_ORDEN_PAGO
     AND A.STATUS != 'AN'
     AND C.DESCRIPCION_ID = A.TIPO_ORDEN_PAGO_ID
     AND C.CODIGO = 'P'
     AND D.CODIGO_ORDEN_PAGO = A.CODIGO_ORDEN_PAGO
     AND E.CODIGO_ORDEN_PAGO = A.CODIGO_ORDEN_PAGO
   GROUP
      BY B.CODIGO_SALDO
        ,A.CODIGO_PRESUPUESTO
        ,A.NUMERO_ORDEN_PAGO
        ,A.FECHA_ORDEN_PAGO
        ,D.MONTO
        ,E.MONTO
        ,A.MOTIVO
;


REATE OR REPLACE FORCE VIEW "PRE"."PRE_V_DOC_COMPROMISOS" ("CODIGO_SALDO", "CODIGO_PRESUPUESTO", "FECHA", "NUMERO", "MOTIVO", "ORIGEN_COMPROMISO", "MONTO") AS
  SELECT B.CODIGO_SALDO
        ,A.CODIGO_PRESUPUESTO
        ,A.FECHA_COMPROMISO FECHA
        ,A.NUMERO_COMPROMISO NUMERO
        ,A.MOTIVO
        ,'COMPROMISO' ORIGEN_COMPROMISO
        ,SUM(B.MONTO-B.MONTO_ANULADO) MONTO
    FROM ADM_COMPROMISOS A
        ,ADM_PUC_COMPROMISO B
   WHERE B.CODIGO_COMPROMISO = A.CODIGO_COMPROMISO
     AND A.STATUS != 'AN'
     AND B.MONTO > 0
   GROUP
      BY B.CODIGO_SALDO
        ,A.CODIGO_PRESUPUESTO
        ,A.FECHA_COMPROMISO
        ,A.NUMERO_COMPROMISO
        ,A.MOTIVO
   UNION ALL
  SELECT C.CODIGO_SALDO
        ,A.CODIGO_PRESUPUESTO
        ,A.FECHA_ORDEN_COMPRA FECHA
        ,A.NUMERO_ORDEN_COMPRA NUMERO
        ,A.MOTIVO
        ,'ORDEN DE COMPRA' ORIGEN_COMPROMISO
        ,SUM(C.MONTO) MONTO
    FROM ADM_ORDEN_COMPRA A
        ,ADM_DETALLE_ORDEN_COMPRA B
        ,ADM_PUC_ORDEN_COMPRA C
   WHERE B.CODIGO_ORDEN_COMPRA = A.CODIGO_ORDEN_COMPRA
     AND C.CODIGO_DETALLE_ORDEN_COMPRA = B.CODIGO_DETALLE_ORDEN_COMPRA
     AND A.STATUS != 'AN'
     AND C.MONTO > 0
   GROUP
      BY C.CODIGO_SALDO
        ,A.CODIGO_PRESUPUESTO
        ,A.FECHA_ORDEN_COMPRA
        ,A.NUMERO_ORDEN_COMPRA
        ,A.MOTIVO
   UNION ALL
  SELECT B.CODIGO_SALDO
        ,A.CODIGO_PRESUPUESTO
        ,A.FECHA_CONTRATO FECHA
        ,A.NUMERO_CONTRATO NUMERO
        ,A.OBRA MOTIVO
        ,'CONTRATO' ORIGEN_COMPROMISO
        ,SUM(B.MONTO-B.MONTO_ANULADO) MONTO
    FROM ADM_CONTRATOS A
        ,ADM_PUC_CONTRATO B
   WHERE B.CODIGO_CONTRATO = A.CODIGO_CONTRATO
     AND A.STATUS != 'AN'
     AND B.MONTO > 0
   GROUP
      BY B.CODIGO_SALDO
        ,A.CODIGO_PRESUPUESTO
        ,A.FECHA_CONTRATO
        ,A.NUMERO_CONTRATO
        ,A.OBRA
   UNION ALL
  SELECT C.CODIGO_SALDO
        ,A.CODIGO_PRESUPUESTO
        ,A.FECHA_COMPROMISO FECHA
        ,A.NUMERO_COMPROMISO NUMERO
        ,A.MOTIVO
        ,'ODC' ORIGEN_COMPROMISO
        ,SUM(C.MONTO) MONTO
    FROM PRE_COMPROMISOS A
        ,PRE_DETALLE_COMPROMISOS B
        ,PRE_PUC_COMPROMISOS C
   WHERE B.CODIGO_COMPROMISO = A.CODIGO_COMPROMISO
     AND C.CODIGO_DETALLE_COMPROMISO = B.CODIGO_DETALLE_COMPROMISO
     AND A.STATUS != 'AN'
     AND C.MONTO > 0
   GROUP
      BY C.CODIGO_SALDO
        ,A.CODIGO_PRESUPUESTO
        ,A.FECHA_COMPROMISO
        ,A.NUMERO_COMPROMISO
        ,A.MOTIVO
;

CREATE OR REPLACE FORCE VIEW "PRE"."PRE_V_DOC_MODIFICADO" ("CODIGO_SALDO", "CODIGO_PRESUPUESTO", "FECHA", "NUMERO", "CODIGO_MODIFICACION", "MOTIVO", "ORIGEN", "MONTO") AS
  SELECT B.CODIGO_SALDO
    ,A.CODIGO_PRESUPUESTO
    ,A.FECHA_MODIFICACION FECHA
    ,SOL.NUMERO_SOL_MODIFICACION NUMERO
    ,A.CODIGO_MODIFICACION
    ,A.MOTIVO
    ,DECODE(B.DE_PARA,'D','Modificación (Desde)','P','Modificación (Para)') ORIGEN
    ,DECODE(B.DE_PARA,'D',-SUM(B.MONTO),'P',SUM(B.MONTO)) MONTO
    FROM PRE_MODIFICACION A
        ,PRE_PUC_MODIFICACION B
        ,PRE_SOL_MODIFICACION SOL
    WHERE SOL.CODIGO_SOL_MODIFICACION = A.CODIGO_SOL_MODIFICACION
    AND B.CODIGO_MODIFICACION = A.CODIGO_MODIFICACION
    AND A.STATUS != 'AN'
GROUP
    BY B.CODIGO_SALDO
    ,A.CODIGO_PRESUPUESTO
    ,A.FECHA_MODIFICACION
    ,A.CODIGO_MODIFICACION
    ,B.DE_PARA
    ,NUMERO_SOL_MODIFICACION
    ,A.MOTIVO;


   CREATE OR REPLACE FORCE VIEW "PRE"."PRE_V_DOC_PAGADO" ("CODIGO_SALDO", "CODIGO_PRESUPUESTO", "FECHA", "NUMERO", "MOTIVO", "MONTO") AS
  SELECT   B.CODIGO_SALDO
        ,A.CODIGO_PRESUPUESTO
        ,A.FECHA_CHEQUE FECHA
        ,A.NUMERO_CHEQUE NUMERO
        ,A.MOTIVO
        ,SUM(B.MONTO-B.MONTO_ANULADO) MONTO
    FROM ADM_CHEQUES A
        ,ADM_PUC_CHEQUE B
   WHERE B.CODIGO_CHEQUE = A.CODIGO_CHEQUE
     AND B.MONTO > 0
     AND A.STATUS != 'AN'
   GROUP
      BY B.CODIGO_SALDO
        ,A.CODIGO_PRESUPUESTO
        ,A.FECHA_CHEQUE
        ,A.NUMERO_CHEQUE
        ,A.MOTIVO;
